// src/resources/js/components/ExampleComponent.jsx
import React from "react";

function ExampleComponent(props) {
    console.log(props);
    return (
        <div>
            <h1>Hello, React!!!</h1>
            {props.message ? <p>{props.message}</p> : null}
            {props.user.name ? <p>{props.user.name}</p> : null}
            {props.user.email ? <p>{props.user.email}</p> : null}
        </div>
    );
}

export default ExampleComponent;

// src/resources/js/components/ExampleComponent.vue
<template>
    <div>
        <h1>Hello, Vue!</h1>
        <p>{{ data.message }}</p>
    </div>
</template>

<script>
export default {
    name: "ExampleComponent",
    props: {
        data: {
            type: Object,
            required: true,
        },
    },
    mounted() {
        console.log(this.data);
    },
};
</script>

<style scoped>
h1 {
    color: blue;
}
</style>
